// Auto-generated by Extension.js. Literal unions for editor Intellisense.
// Do not edit manually.
declare namespace ExtensionPaths {
  type KnownPublic =
    | 'public/extension.svg'
    | 'public/logo.svg'
    | '/public/extension.svg'
    | '/public/logo.svg'
    | '/extension.svg'
    | '/logo.svg'
  type KnownPages = never
  type KnownScripts = never
  type KnownPath = KnownPublic | KnownPages | KnownScripts
}

// Helper overload for IDEs: getURL only accepts known paths
declare function __extensionjs_getURL<Path extends ExtensionPaths.KnownPath>(
  p: Path
): string
export {}
