packages:
  - './programs/cli'
  - './programs/create'
  - './programs/develop'
  # Future extraction: chromium runner core package (placeholder only)
  - './programs/develop/webpack/plugin-browsers/run-chromium'
  - './extensions/*'
  - './templates/*'
  # Ignore dist folders used for testing
  - "!programs/cli/dist"
  - "!programs/develop/dist"
onlyBuiltDependencies:
  - "@ast-grep/napi"
  - "@ast-grep/napi-win32-x64-msvc"
  - "@parcel/watcher"
  - "@swc/core"
  - "core-js"
  - "esbuild"
  - "less"
  