//  ██████╗██╗     ██╗
// ██╔════╝██║     ██║
// ██║     ██║     ██║
// ██║     ██║     ██║
// ╚██████╗███████╗██║
//  ╚═════╝╚══════╝╚═╝
// MIT License (c) 2020–present Cezar Augusto & the Extension.js authors, presence implies inheritance

// GENERATED by scripts/generate-template-corpus.mjs. Do not edit by hand.
// These are the folders extension-js/examples publishes under examples/ at
// the exact commit extension-create downloads from, so the names the CLI
// advertises and the names it can scaffold are one list.

export const TEMPLATE_CORPUS_REPO = 'extension-js/examples'

export const TEMPLATE_CORPUS_REF = '787c974573f6ed70107e331e261924d20de64740'

export const TEMPLATE_CORPUS_SLUGS: readonly string[] = [
  'action',
  'action-locales',
  'ai-chatgpt',
  'ai-claude',
  'ai-gemini',
  'ai-perplexity',
  'content',
  'content-css-modules',
  'content-custom-font',
  'content-env',
  'content-less',
  'content-less-modules',
  'content-main-world',
  'content-multi-one-entry',
  'content-multi-three-entries',
  'content-preact',
  'content-react',
  'content-sass',
  'content-sass-modules',
  'content-svelte',
  'content-typescript',
  'content-vue',
  'devtools',
  'devtools-preact',
  'devtools-react',
  'devtools-svelte',
  'devtools-typescript',
  'devtools-vue',
  'init',
  'javascript',
  'newtab',
  'newtab-browser-flags',
  'newtab-config-eslint',
  'newtab-config-prettier',
  'newtab-config-stylelint',
  'newtab-crypto',
  'newtab-env',
  'newtab-less',
  'newtab-preact',
  'newtab-react',
  'newtab-react-router',
  'newtab-sass',
  'newtab-svelte',
  'newtab-typescript',
  'newtab-vue',
  'playwright',
  'preact',
  'react',
  'sidebar',
  'sidebar-antd',
  'sidebar-monorepo-nx',
  'sidebar-monorepo-turborepo',
  'sidebar-shadcn',
  'special-folders-pages',
  'special-folders-scripts',
  'svelte',
  'transformers-js',
  'typescript',
  'vue'
]
