//  ██████╗██╗     ██╗
// ██╔════╝██║     ██║
// ██║     ██║     ██║
// ██║     ██║     ██║
// ╚██████╗███████╗██║
//  ╚═════╝╚══════╝╚═╝
// MIT License (c) 2020–present Cezar Augusto & the Extension.js authors, presence implies inheritance

// GENERATED by scripts/generate-template-corpus.mjs. Do not edit by hand.
// These are the folders extension-js/examples publishes under examples/ at
// the exact commit extension-create downloads from, so the names the CLI
// advertises and the names it can scaffold are one list.

export const TEMPLATE_CORPUS_REPO = 'extension-js/examples'

export const TEMPLATE_CORPUS_REF = 'f7f4e6efb56a7e5ae08d58dbff3972d94af7d021'

export const TEMPLATE_CORPUS_SLUGS: readonly string[] = [
  'action',
  'action-locales',
  'ai-chatgpt',
  'ai-claude',
  'ai-gemini',
  'ai-perplexity',
  'content',
  'content-css-modules',
  'content-custom-font',
  'content-env',
  'content-less',
  'content-less-modules',
  'content-main-world',
  'content-multi-one-entry',
  'content-multi-three-entries',
  'content-preact',
  'content-react',
  'content-sass',
  'content-sass-modules',
  'content-svelte',
  'content-typescript',
  'content-vue',
  'init',
  'javascript',
  'new',
  'new-browser-flags',
  'new-config-eslint',
  'new-config-prettier',
  'new-config-stylelint',
  'new-crypto',
  'new-env',
  'new-less',
  'new-preact',
  'new-react',
  'new-react-router',
  'new-sass',
  'new-svelte',
  'new-typescript',
  'new-vue',
  'playwright',
  'preact',
  'react',
  'sidebar',
  'sidebar-antd',
  'sidebar-monorepo-turborepo',
  'sidebar-shadcn',
  'special-folders-pages',
  'special-folders-scripts',
  'svelte',
  'transformers-js',
  'typescript',
  'vue'
]
