import * as path from 'path'
import * as fs from 'fs'

// Extract CSS imports from the source file
function extractCSSImports(source: string): string[] {
  const cssImports: string[] = []

  // Split source into lines and process each line
  const lines = source.split('\n')

  // Match various CSS import patterns (excluding commented lines)
  const cssImportPatterns = [
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]/,
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]\s*;?\s*$/,
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]\s*from\s+['"][^'"]*['"]/
  ]

  for (const line of lines) {
    // Skip commented lines
    const trimmedLine = line.trim()
    if (trimmedLine.startsWith('//') || trimmedLine.startsWith('/*')) {
      continue
    }

    for (const pattern of cssImportPatterns) {
      const match = pattern.exec(line)
      if (match) {
        const cssPath = match[1]
        if (cssPath && !cssImports.includes(cssPath)) {
          cssImports.push(cssPath)
        }
      }
    }
  }

  return cssImports
}

export function generateSvelteWrapperCode(
  source: string,
  resourcePath: string
): string {
  const fileName = path.basename(resourcePath, path.extname(resourcePath))
  const cssImports = extractCSSImports(source)
  const resourceDir = path.dirname(resourcePath)

  console.log(
    `[Extension.js] Detected Svelte framework with CSS imports:`,
    cssImports
  )

  // Read CSS content at build time for hardcoding
  const cssContentMap: Record<string, string> = {}
  for (const cssImport of cssImports) {
    try {
      const cssPath = path.resolve(resourceDir, cssImport)
      if (fs.existsSync(cssPath)) {
        const cssContent = fs.readFileSync(cssPath, 'utf-8')
        // Escape the CSS content for JavaScript string
        const escapedCSS = cssContent
          .replace(/\\/g, '\\\\')
          .replace(/`/g, '\\`')
          .replace(/\${/g, '\\${')
          .replace(/\n/g, ' ')
          .replace(/\s+/g, ' ')
          .trim()
        cssContentMap[cssImport] = escapedCSS
        console.log(
          `[Extension.js] Read CSS content for ${cssImport}, length: ${cssContent.length}`
        )
      } else {
        console.warn(`[Extension.js] CSS file not found: ${cssPath}`)
      }
    } catch (error) {
      console.warn(
        `[Extension.js] Failed to read CSS file ${cssImport}:`,
        error
      )
    }
  }

  // Generate TypeScript-compatible code for Svelte
  const wrapperCode = `
// Svelte Content Script Wrapper - Auto-generated by Extension.js
// This wrapper provides Shadow DOM isolation and CSS injection for Svelte content scripts

// Original Svelte content script source (directive processed)
${source.replace(/'use shadow-dom'/g, "// 'use shadow-dom'").replace(/"use shadow-dom"/g, '// "use shadow-dom"')}

// Content script options interface
export interface ContentScriptOptions {
  rootElement?: string
  rootClassName?: string
  stylesheets?: string[]
}

// Content script instance interface
export interface ContentScriptInstance {
  mount: (container: HTMLElement) => void
  unmount: () => void
}

// Svelte Content script wrapper class
class SvelteContentScriptWrapper {
  private rootElement: HTMLElement | null = null
  private shadowRoot: ShadowRoot | null = null
  private styleElement: HTMLStyleElement | null = null
  private renderFunction: (container: HTMLElement) => (() => void) | void
  private unmountFunction: (() => void) | null = null
  private options: ContentScriptOptions

  constructor(renderFunction: (container: HTMLElement) => (() => void) | void, options: ContentScriptOptions = {}) {
    this.renderFunction = renderFunction
    this.options = {
      rootElement: 'extension-root',
      rootClassName: undefined, // Svelte handles its own styling
      stylesheets: ${JSON.stringify(cssImports.length > 0 ? cssImports : ['./styles.css'])},
      ...options
    }
  }

  async mount(container?: HTMLElement): Promise<void> {
    console.log('[Extension.js] Svelte wrapper mount called')
    if (this.rootElement) {
      this.unmount()
    }

    // Create root element - Svelte handles its own container styling
    this.rootElement = container || document.createElement('div')
    this.rootElement.id = this.options.rootElement!
    if (this.options.rootClassName) {
      this.rootElement.className = this.options.rootClassName
    }
    // Svelte component handles its own styling

    // Create shadow root for style isolation
    this.shadowRoot = this.rootElement.attachShadow({ mode: 'open' })

    // Inject styles FIRST
    console.log('[Extension.js] About to inject styles')
    await this.injectStyles()

    // Render Svelte content
    console.log('[Extension.js] About to render Svelte content')
    const result = this.renderFunction(this.shadowRoot as any)
    if (typeof result === 'function') {
      this.unmountFunction = result
    }

    // Append to document if no container provided
    if (!container) {
      document.body.appendChild(this.rootElement)
    }
    
    console.log('[Extension.js] Svelte wrapper mount complete')
  }

  unmount() {
    if (this.unmountFunction) {
      this.unmountFunction()
      this.unmountFunction = null
    }

    if (this.rootElement && this.rootElement.parentNode) {
      this.rootElement.parentNode.removeChild(this.rootElement)
    }

    this.rootElement = null
    this.shadowRoot = null
    this.styleElement = null
  }

  // Inject styles with hardcoded CSS content for Svelte templates
  private async injectStyles(): Promise<void> {
    console.log('[Extension.js] Svelte injectStyles called')
    const targetRoot = this.shadowRoot || this.rootElement!

    // Create style element
    this.styleElement = document.createElement('style')
    targetRoot.appendChild(this.styleElement)

    // Fetch CSS content
    try {
      console.log('[Extension.js] About to fetch CSS')
      const cssContent = await this.fetchCSS()
      console.log('[Extension.js] CSS fetched, length:', cssContent.length)
      this.styleElement.textContent = cssContent
      console.log('[Extension.js] Svelte CSS injected successfully')
    } catch (error) {
      console.error('[Extension.js] Failed to inject Svelte CSS:', error)
    }

    // Setup HMR for CSS files
    this.setupCSSHMR()
  }

  // Fetch CSS with hardcoded content for Svelte templates
  private async fetchCSS(): Promise<string> {
    let allCSS = ''
    
    console.log('[Extension.js] Processing Svelte stylesheets:', this.options.stylesheets)
    
    // CSS content map is injected at build time
    const cssContentMap: Record<string, string> = ${JSON.stringify(cssContentMap)}
    
    for (const stylesheet of this.options.stylesheets) {
      try {
        console.log('[Extension.js] Processing Svelte stylesheet:', stylesheet)
        // Check if we have hardcoded content for this stylesheet
        if (cssContentMap[stylesheet]) {
          const cssContent = cssContentMap[stylesheet]
          allCSS += cssContent + '\\n'
          console.log(\`[Extension.js] Successfully injected Svelte \${stylesheet} content\`)
          continue
        }
        
        // For stylesheets without hardcoded content, try to fetch them
        const cssUrl = new URL(stylesheet, import.meta.url)
        const response = await fetch(cssUrl)
        const text = await response.text()
        if (response.ok) {
          allCSS += text + '\\n'
          console.log('[Extension.js] Successfully fetched stylesheet:', stylesheet)
        } else {
          console.warn('[Extension.js] Failed to fetch CSS:', stylesheet)
        }
      } catch (error) {
        console.warn('[Extension.js] Failed to fetch Svelte CSS:', stylesheet, error)
      }
    }
    
    return allCSS
  }

  // Setup CSS HMR for Svelte templates
  private setupCSSHMR() {
    if (!import.meta.webpackHot) return

    // Setup HMR for each CSS file
    for (const stylesheet of this.options.stylesheets) {
      import.meta.webpackHot?.accept(stylesheet, async () => {
        try {
          const cssContent = await this.fetchCSS()
          if (this.styleElement) {
            this.styleElement.textContent = cssContent
            console.log('[Extension.js] Svelte CSS updated via HMR:', stylesheet)
          }
        } catch (error) {
          console.error('[Extension.js] Failed to update Svelte CSS via HMR:', stylesheet, error)
        }
      })
    }
  }
}

// Initialize Svelte content script with wrapper
function initializeSvelteContentScript(
  options: ContentScriptOptions,
  renderFunction: (container: HTMLElement) => (() => void) | void
): ContentScriptInstance {
  const wrapper = new SvelteContentScriptWrapper(renderFunction, options)
  
  return {
    mount: (container?: HTMLElement) => wrapper.mount(container),
    unmount: () => wrapper.unmount()
  }
}

// Auto-initialize the Svelte content script with the wrapper
export function autoInitializeSvelteContentScript(
  options: ContentScriptOptions = {}
): ContentScriptInstance {
  // Get the render function from the imported contentScript
  const renderFunction = contentScript(options)

  // Initialize with the wrapper using the detected CSS imports
  return initializeSvelteContentScript(options, renderFunction)
}

// Simple initialization for Svelte
let unmount: (() => void) | undefined

async function initialize() {
  console.log('[Extension.js] Svelte wrapper initialize called')
  if (unmount) {
    console.log('[Extension.js] Unmounting previous Svelte instance')
    unmount()
  }
  
  // Get the render function from the contentScript function
  const renderFunction = contentScript({})
  const wrapper = new SvelteContentScriptWrapper(renderFunction, {})
  await wrapper.mount()
  unmount = () => wrapper.unmount()
  console.log('[Extension.js] Svelte wrapper initialization complete')
}

if (import.meta.webpackHot) {
  import.meta.webpackHot?.accept()
  import.meta.webpackHot?.dispose(() => unmount?.())

  // Accept changes to this file
  import.meta.webpackHot?.accept(() => {
    initialize()
  })
}

if (document.readyState === 'complete') {
  initialize()
} else {
  document.addEventListener('readystatechange', () => {
    if (document.readyState === 'complete') {
      initialize()
    }
  })
}

export default SvelteContentScriptWrapper
`

  return wrapperCode
}
