import * as path from 'path'
import * as fs from 'fs'

// Extract CSS imports from the source file
function extractCSSImports(source: string): string[] {
  const cssImports: string[] = []

  // Split source into lines and process each line
  const lines = source.split('\n')

  // Match various CSS import patterns (excluding commented lines)
  const cssImportPatterns = [
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]/,
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]\s*;?\s*$/,
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]\s*from\s+['"][^'"]*['"]/
  ]

  for (const line of lines) {
    // Skip commented lines
    const trimmedLine = line.trim()
    if (trimmedLine.startsWith('//') || trimmedLine.startsWith('/*')) {
      continue
    }

    for (const pattern of cssImportPatterns) {
      const match = pattern.exec(line)
      if (match) {
        const cssPath = match[1]
        if (cssPath && !cssImports.includes(cssPath)) {
          cssImports.push(cssPath)
        }
      }
    }
  }

  return cssImports
}

export function generateTypeScriptWrapperCode(
  source: string,
  resourcePath: string
): string {
  const fileName = path.basename(resourcePath, path.extname(resourcePath))
  const cssImports = extractCSSImports(source)
  const resourceDir = path.dirname(resourcePath)

  if (process.env.EXTENSION_ENV === 'development') {
    console.log(
      `[Extension.js] Detected TypeScript framework with CSS imports:`,
      cssImports
    )
  }

  // Read CSS content at build time for hardcoding
  const cssContentMap: Record<string, string> = {}
  for (const cssImport of cssImports) {
    try {
      const cssPath = path.resolve(resourceDir, cssImport)
      if (fs.existsSync(cssPath)) {
        const cssContent = fs.readFileSync(cssPath, 'utf-8')
        // Escape the CSS content for JavaScript string
        const escapedCSS = cssContent
          .replace(/\\/g, '\\\\')
          .replace(/`/g, '\\`')
          .replace(/\${/g, '\\${')
          .replace(/\n/g, ' ')
          .replace(/\s+/g, ' ')
          .trim()
        cssContentMap[cssImport] = escapedCSS
        if (process.env.EXTENSION_ENV === 'development') {
          console.log(
            `[Extension.js] Read CSS content for ${cssImport}, length: ${cssContent.length}`
          )
        }
      } else {
        if (process.env.EXTENSION_ENV === 'development') {
          console.warn(`[Extension.js] CSS file not found: ${cssPath}`)
        }
      }
    } catch (error) {
      if (process.env.EXTENSION_ENV === 'development') {
        console.warn(
          `[Extension.js] Failed to read CSS file ${cssImport}:`,
          error
        )
      }
    }
  }

  // Normalize default export to an internal alias so wrappers are name-agnostic
  function normalizeDefaultExport(input: string) {
    const hasDefault = /\bexport\s+default\s+/.test(input)
    if (!hasDefault) return {code: input, hasDefault}
    const replaced = input.replace(
      /\bexport\s+default\s+/,
      'const __extensionjs_default = '
    )
    return {
      code: replaced + '\n;export default __extensionjs_default',
      hasDefault
    }
  }
  const {code: normalizedSource, hasDefault} = normalizeDefaultExport(source)

  // Generate TypeScript-compatible code
  const wrapperCode = `
// TypeScript Content Script Wrapper - Auto-generated by Extension.js
// This wrapper provides Shadow DOM isolation and CSS injection for TypeScript content scripts

// Original TypeScript content script source (directive processed)
${normalizedSource.replace(/'use shadow-dom'/g, "// 'use shadow-dom'").replace(/"use shadow-dom"/g, '// "use shadow-dom"')}

// Content script options interface
export interface ContentScriptOptions {
  rootElement?: string
  rootClassName?: string
  stylesheets?: string[]
}

// Content script instance interface
export interface ContentScriptInstance {
  mount: (container: HTMLElement) => void
  unmount: () => void
}

// TypeScript Content script wrapper class
class TypeScriptContentScriptWrapper {
  private rootElement: HTMLElement | null = null
  private shadowRoot: ShadowRoot | null = null
  private styleElement: HTMLStyleElement | null = null
  private renderFunction: (container: HTMLElement) => (() => void) | void
  private unmountFunction: (() => void) | null = null
  private options: ContentScriptOptions

  constructor(renderFunction: (container: HTMLElement) => (() => void) | void, options: ContentScriptOptions = {}) {
    this.renderFunction = renderFunction
    this.options = {
      rootElement: 'extension-root',
      rootClassName: undefined, // TypeScript handles its own styling
      stylesheets: ${JSON.stringify(cssImports)},
      ...options
    }
  }

  async mount(container?: HTMLElement): Promise<void> {
    console.log('[Extension.js] TypeScript wrapper mount called')
    if (this.rootElement) {
      this.unmount()
    }

    // Create root element - TypeScript handles its own container styling
    this.rootElement = container || document.createElement('div')
    this.rootElement.id = this.options.rootElement!
    if (this.options.rootClassName) {
      this.rootElement.className = this.options.rootClassName
    }

    // Create shadow root for style isolation
    this.shadowRoot = this.rootElement.attachShadow({ mode: 'open' })

    // Inject styles FIRST
    console.log('[Extension.js] About to inject styles')
    await this.injectStyles()

    // Render TypeScript content
    console.log('[Extension.js] About to render TypeScript content')
    const result = this.renderFunction(this.shadowRoot as any)
    if (typeof result === 'function') {
      this.unmountFunction = result
    }

    // Append to document if no container provided
    if (!container) {
      document.body.appendChild(this.rootElement)
    }
    
    console.log('[Extension.js] TypeScript wrapper mount complete')
  }

  unmount() {
    if (this.unmountFunction) {
      this.unmountFunction()
      this.unmountFunction = null
    }

    if (this.rootElement && this.rootElement.parentNode) {
      this.rootElement.parentNode.removeChild(this.rootElement)
    }

    this.rootElement = null
    this.shadowRoot = null
    this.styleElement = null
  }

  // Inject styles with hardcoded CSS content for TypeScript templates
  private async injectStyles(): Promise<void> {
    console.log('[Extension.js] TypeScript injectStyles called')
    const targetRoot = this.shadowRoot || this.rootElement!

    // Create style element
    this.styleElement = document.createElement('style')
    targetRoot.appendChild(this.styleElement)

    // Fetch CSS content
    try {
      console.log('[Extension.js] About to fetch CSS')
      const cssContent = await this.fetchCSS()
      console.log('[Extension.js] CSS fetched, length:', cssContent.length)
      this.styleElement.textContent = cssContent
      console.log('[Extension.js] TypeScript CSS injected successfully')
    } catch (error) {
      console.error('[Extension.js] Failed to inject TypeScript CSS:', error)
    }

    // Setup HMR for CSS files
    this.setupCSSHMR()
  }

  // Fetch CSS with hardcoded content for TypeScript templates
  private async fetchCSS(): Promise<string> {
    let allCSS = ''
    
    console.log('[Extension.js] Processing TypeScript stylesheets:', this.options.stylesheets)
    
    // CSS content map is injected at build time
    const cssContentMap: Record<string, string> = ${JSON.stringify(cssContentMap)}
    
    for (const stylesheet of this.options.stylesheets) {
      try {
        console.log('[Extension.js] Processing TypeScript stylesheet:', stylesheet)
        // Check if we have hardcoded content for this stylesheet
        if (cssContentMap[stylesheet]) {
          const cssContent = cssContentMap[stylesheet]
          allCSS += cssContent + '\\n'
          console.log(\`[Extension.js] Successfully injected TypeScript \${stylesheet} content\`)
          continue
        }
        
        // For stylesheets without hardcoded content, try to fetch them
        const cssUrl = new URL(stylesheet, import.meta.url)
        const response = await fetch(cssUrl)
        const text = await response.text()
        if (response.ok) {
          allCSS += text + '\\n'
          console.log('[Extension.js] Successfully fetched stylesheet:', stylesheet)
        } else {
          console.warn('[Extension.js] Failed to fetch CSS:', stylesheet)
        }
      } catch (error) {
        console.warn('[Extension.js] Failed to fetch TypeScript CSS:', stylesheet, error)
      }
    }
    
    return allCSS
  }

  // Setup CSS HMR for TypeScript templates
  private setupCSSHMR() {
    if (!import.meta.webpackHot) return

    // Setup HMR for each CSS file
    for (const stylesheet of this.options.stylesheets) {
      import.meta.webpackHot?.accept(stylesheet, async () => {
        try {
          const cssContent = await this.fetchCSS()
          if (this.styleElement) {
            this.styleElement.textContent = cssContent
            console.log('[Extension.js] TypeScript CSS updated via HMR:', stylesheet)
          }
        } catch (error) {
          console.error('[Extension.js] Failed to update TypeScript CSS via HMR:', stylesheet, error)
        }
      })
    }
  }
}

// Initialize TypeScript content script with wrapper
function initializeTypeScriptContentScript(
  options: ContentScriptOptions,
  renderFunction: (container: HTMLElement) => (() => void) | void
): ContentScriptInstance {
  const wrapper = new TypeScriptContentScriptWrapper(renderFunction, options)
  
  return {
    mount: (container?: HTMLElement) => wrapper.mount(container),
    unmount: () => wrapper.unmount()
  }
}

// Auto-initialize the TypeScript content script with the wrapper
export function autoInitializeTypeScriptContentScript(
  options: ContentScriptOptions = {}
): ContentScriptInstance {
  // Get the render function from the default export if provided
  const renderFunction = typeof __extensionjs_default === 'function' ? __extensionjs_default(options) : undefined

  if (!renderFunction) {
    console.warn('[Extension.js] No default export function found in', ${JSON.stringify(fileName)}, '\\n- Wrapper skipped for backward compatibility.\\n- Starting in v3 this will be required.')
    return { mount: () => {}, unmount: () => {} }
  }

  // Initialize with the wrapper using the detected CSS imports
  return initializeTypeScriptContentScript(options, renderFunction)
}

// Simple initialization for TypeScript
let __extensionjs_unmount: (() => void) | undefined

async function initialize() {
  console.log('[Extension.js] TypeScript wrapper initialize called')
  if (__extensionjs_unmount) {
    console.log('[Extension.js] Unmounting previous TypeScript instance')
    __extensionjs_unmount()
  }
  
  // Get the render function from the default export if provided
  const renderFunction = typeof __extensionjs_default === 'function' ? __extensionjs_default({}) : undefined
  if (!renderFunction) return
  const wrapper = new TypeScriptContentScriptWrapper(renderFunction, {})
  await wrapper.mount()
  __extensionjs_unmount = () => wrapper.unmount()
  console.log('[Extension.js] TypeScript wrapper initialization complete')
}

if (import.meta.webpackHot) {
  import.meta.webpackHot?.accept()
  import.meta.webpackHot?.dispose(() => __extensionjs_unmount?.())

  // Accept changes to this file
  import.meta.webpackHot?.accept(() => {
    initialize()
  })
}

if (document.readyState === 'complete') {
  initialize()
} else {
  document.addEventListener('readystatechange', () => {
    if (document.readyState === 'complete') {
      initialize()
    }
  })
}

export default TypeScriptContentScriptWrapper
`

  return wrapperCode
}
