import * as path from 'path'
import * as fs from 'fs'

// Extract CSS imports from the source file
function extractCSSImports(source: string): string[] {
  const cssImports: string[] = []

  // Split source into lines and process each line
  const lines = source.split('\n')

  // Match various CSS import patterns (excluding commented lines)
  const cssImportPatterns = [
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]/,
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]\s*;?\s*$/,
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]\s*from\s+['"][^'"]*['"]/
  ]

  for (const line of lines) {
    // Skip commented lines
    const trimmedLine = line.trim()
    if (trimmedLine.startsWith('//') || trimmedLine.startsWith('/*')) {
      continue
    }

    for (const pattern of cssImportPatterns) {
      const match = pattern.exec(line)
      if (match) {
        const cssPath = match[1]
        if (cssPath && !cssImports.includes(cssPath)) {
          cssImports.push(cssPath)
        }
      }
    }
  }

  return cssImports
}

export function generateJavaScriptWrapperCode(
  source: string,
  resourcePath: string
): string {
  const fileName = path.basename(resourcePath, path.extname(resourcePath))
  const cssImports = extractCSSImports(source)
  const resourceDir = path.dirname(resourcePath)

  // Normalize default export to an internal alias so wrappers are name-agnostic
  function normalizeDefaultExport(input: string) {
    const hasDefault = /\bexport\s+default\s+/.test(input)
    if (!hasDefault) return {code: input, hasDefault}
    const replaced = input.replace(
      /\bexport\s+default\s+/,
      'const __extensionjs_default = '
    )
    return {
      code: replaced + '\n;export default __extensionjs_default',
      hasDefault
    }
  }
  const {code: normalizedSource, hasDefault} = normalizeDefaultExport(source)
  const userHmrInSource = /import\.meta\.(webpackHot|hot)|module\.hot/.test(
    source
  )

  if (process.env.EXTENSION_ENV === 'development') {
    console.log(
      `[Extension.js] Detected JavaScript framework with CSS imports:`,
      cssImports
    )
  }

  // Read CSS content at build time for hardcoding
  const cssContentMap: Record<string, string> = {}
  for (const cssImport of cssImports) {
    try {
      const cssPath = path.resolve(resourceDir, cssImport)
      if (fs.existsSync(cssPath)) {
        const cssContent = fs.readFileSync(cssPath, 'utf-8')
        // Escape the CSS content for JavaScript string
        const escapedCSS = cssContent
          .replace(/\\/g, '\\\\')
          .replace(/`/g, '\\`')
          .replace(/\${/g, '\\${')
          .replace(/\n/g, ' ')
          .replace(/\s+/g, ' ')
          .trim()
        cssContentMap[cssImport] = escapedCSS
        if (process.env.EXTENSION_ENV === 'development') {
          console.log(
            `[Extension.js] Read CSS content for ${cssImport}, length: ${cssContent.length}`
          )
        }
      } else {
        if (process.env.EXTENSION_ENV === 'development') {
          console.warn(`[Extension.js] CSS file not found: ${cssPath}`)
        }
      }
    } catch (error) {
      if (process.env.EXTENSION_ENV === 'development') {
        console.warn(
          `[Extension.js] Failed to read CSS file ${cssImport}:`,
          error
        )
      }
    }
  }

  // Prepare processed and safely escaped original source for embedding
  const processedSource = normalizedSource
    .replace(/'use shadow-dom'/g, "// 'use shadow-dom'")
    .replace(/"use shadow-dom"/g, '// "use shadow-dom"')

  // Escape template literal delimiters and interpolations to avoid breaking wrapper template
  const escapedProcessedSource = processedSource
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\\${')

  // Generate JavaScript-compatible wrapper code
  const wrapperCode = `
// JavaScript Content Script Wrapper - Auto-generated by Extension.js
// This wrapper provides Shadow DOM isolation and CSS injection for JavaScript content scripts

// Original JavaScript content script source (directive processed)
${escapedProcessedSource}

// Dev flags baked at build time
const __EXT_JS_DEV__ = process.env.EXTENSION_ENV !== 'production'
const __EXT_USER_HMR__ = ${userHmrInSource ? 'true' : 'false'}
const __EXT_HAS_DEFAULT__ = ${hasDefault ? 'true' : 'false'}

// Content script wrapper class
class JavaScriptContentScriptWrapper {
  constructor(renderFunction, options = {}) {
    this.renderFunction = renderFunction
    this.options = {
      rootElement: 'extension-root',
      rootClassName: undefined,
      stylesheets: ${JSON.stringify(cssImports)},
      ...options
    }
    this.rootElement = null
    this.shadowRoot = null
    this.styleElement = null
    this.unmountFunction = null
    this.sideEffectNodes = []
  }

  async mount(container) {
    if (this.rootElement) {
      this.unmount()
    }

    // Create root element
    this.rootElement = container || document.createElement('div')
    this.rootElement.id = this.options.rootElement
    if (this.options.rootClassName) {
      this.rootElement.className = this.options.rootClassName
    }

    // Create shadow root for style isolation
    this.shadowRoot = this.rootElement.attachShadow({ mode: 'open' })

    // Inject styles FIRST
    await this.injectStyles()

    // Render content using the original contentScript function or support side-effect defaults
    if (typeof this.renderFunction === 'function') {
      const result = this.renderFunction(this.shadowRoot)
      if (typeof result === 'function') {
        this.unmountFunction = result
      }
    } else {
      const before = Array.from(document.body.children)
      try { (__extensionjs_default)?.({}) } catch {}
      const after = Array.from(document.body.children)
      this.sideEffectNodes = after.filter((n) => !before.includes(n))
    }

    // Append to document if no container provided
    if (!container) {
      document.body.appendChild(this.rootElement)
    }
  }

  unmount() {
    if (this.unmountFunction) {
      this.unmountFunction()
      this.unmountFunction = null
    }

    if (this.sideEffectNodes && this.sideEffectNodes.length) {
      for (const node of this.sideEffectNodes) {
        try { node.parentNode && node.parentNode.removeChild(node) } catch {}
      }
      this.sideEffectNodes = []
    }

    if (this.rootElement && this.rootElement.parentNode) {
      this.rootElement.parentNode.removeChild(this.rootElement)
    }

    this.rootElement = null
    this.shadowRoot = null
    this.styleElement = null
  }

  async injectStyles() {
    const targetRoot = this.shadowRoot || this.rootElement

    // Create style element
    this.styleElement = document.createElement('style')
    targetRoot.appendChild(this.styleElement)

    // Fetch CSS content
    try {
      const cssContent = await this.fetchCSS()
      this.styleElement.textContent = cssContent
    } catch (error) {
      console.error('[Extension.js] Failed to inject JavaScript CSS:', error)
    }

    // Setup HMR for CSS files
    this.setupCSSHMR()
  }

  async fetchCSS() {
    let allCSS = ''
    
    // CSS content map is injected at build time
    const cssContentMap = ${JSON.stringify(cssContentMap)}
    
    for (const stylesheet of this.options.stylesheets) {
      try {
        // Check if we have hardcoded content for this stylesheet
        if (cssContentMap[stylesheet]) {
          const cssContent = cssContentMap[stylesheet]
          allCSS += cssContent + '\\n'
          continue
        }
        
        // For stylesheets without hardcoded content, try to fetch them
        const cssUrl = new URL(stylesheet, import.meta.url)
        const response = await fetch(cssUrl)
        const text = await response.text()
        if (response.ok) {
          allCSS += text + '\\n'
        } else {
          console.warn('[Extension.js] Failed to fetch CSS:', stylesheet)
        }
      } catch (error) {
        console.warn('[Extension.js] Failed to fetch JavaScript CSS:', stylesheet, error)
      }
    }
    
    return allCSS
  }

  setupCSSHMR() {
    if (!import.meta.webpackHot) return

    // Setup HMR for each CSS file
    for (const stylesheet of this.options.stylesheets) {
      import.meta.webpackHot?.accept(stylesheet, async () => {
        try {
          const cssContent = await this.fetchCSS()
          if (this.styleElement) {
            this.styleElement.textContent = cssContent
          }
        } catch (error) {
          console.error('[Extension.js] Failed to update JavaScript CSS via HMR:', stylesheet, error)
        }
      })
    }
  }
}

// Initialize JavaScript content script with wrapper
function initializeJavaScriptContentScript(options, renderFunction) {
  const wrapper = new JavaScriptContentScriptWrapper(renderFunction, options)
  
  return {
    mount: (container) => wrapper.mount(container),
    unmount: () => wrapper.unmount()
  }
}

// Auto-initialize the JavaScript content script with the wrapper
export function autoInitializeJavaScriptContentScript(options = {}) {
  // Get the render function from the imported contentScript
  const renderFunction = typeof __extensionjs_default === 'function' ? __extensionjs_default(options) : null

  if (!renderFunction) {
    if (__EXT_JS_DEV__ && !__EXT_HAS_DEFAULT__) {
      console.warn('[Extension.js] No default export function found in', ${JSON.stringify(fileName)}, '\\n- Wrapper skipped for backward compatibility.\\n- Starting in v3 this will be required.')
    }
    return {
      mount: () => {},
      unmount: () => {}
    }
  }

  // Initialize with the wrapper using the detected CSS imports
  return initializeJavaScriptContentScript(options, renderFunction)
}

// Simple initialization for JavaScript
let unmount

async function initialize() {
  if (unmount) {
    unmount()
  }
  
  const renderFunction = typeof __extensionjs_default === 'function' ? __extensionjs_default({}) : null
  if (!renderFunction) return
  const wrapper = new JavaScriptContentScriptWrapper(renderFunction, {})
  await wrapper.mount()
  unmount = () => wrapper.unmount()

  if (__EXT_JS_DEV__) {
    if (__EXT_USER_HMR__) {
      console.warn('[Extension.js] Detected user HMR code in content script. Please remove it; wrapper provides HMR. Keeping it may cause odd behavior.')
    }
    if (typeof renderFunction === 'function' && typeof renderFunction.name === 'string') {
      console.warn('[Extension.js] Default export returned a cleanup function. Wrapper will call it for back-compat, but please remove returning cleanup; wrapper provides unmount.')
    }
  }
}

if (import.meta.webpackHot) {
  import.meta.webpackHot?.accept()
  import.meta.webpackHot?.dispose(() => unmount?.())

  // Accept changes to this file
  import.meta.webpackHot?.accept(() => {
    initialize()
  })
}

if (document.readyState === 'complete') {
  initialize()
} else {
  document.addEventListener('readystatechange', () => {
    if (document.readyState === 'complete') {
      initialize()
    }
  })
}

export default JavaScriptContentScriptWrapper
`

  return wrapperCode
}
