import * as path from 'path'
import * as fs from 'fs'

// Extract CSS imports from the source file
function extractCSSImports(source: string): string[] {
  const cssImports: string[] = []

  // Split source into lines and process each line
  const lines = source.split('\n')

  // Match various CSS import patterns (excluding commented lines)
  const cssImportPatterns = [
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]/,
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]\s*;?\s*$/,
    /^\s*import\s+['"]([^'"]*\.(?:css|scss|sass|less|module\.css))['"]\s*from\s+['"][^'"]*['"]/
  ]

  for (const line of lines) {
    // Skip commented lines
    const trimmedLine = line.trim()
    if (trimmedLine.startsWith('//') || trimmedLine.startsWith('/*')) {
      continue
    }

    for (const pattern of cssImportPatterns) {
      const match = pattern.exec(line)
      if (match) {
        const cssPath = match[1]
        if (cssPath && !cssImports.includes(cssPath)) {
          cssImports.push(cssPath)
        }
      }
    }
  }

  return cssImports
}

export function generateReactWrapperCode(
  source: string,
  resourcePath: string
): string {
  const fileName = path.basename(resourcePath, path.extname(resourcePath))
  const cssImports = extractCSSImports(source)
  const resourceDir = path.dirname(resourcePath)

  if (process.env.EXTENSION_ENV === 'development') {
    console.log(
      `[Extension.js] Detected React framework with CSS imports:`,
      cssImports
    )
  }

  // Read CSS content at build time for hardcoding
  const cssContentMap: Record<string, string> = {}
  for (const cssImport of cssImports) {
    try {
      const cssPath = path.resolve(resourceDir, cssImport)
      if (fs.existsSync(cssPath)) {
        const cssContent = fs.readFileSync(cssPath, 'utf-8')
        // Escape the CSS content for JavaScript string
        const escapedCSS = cssContent
          .replace(/\\/g, '\\\\')
          .replace(/`/g, '\\`')
          .replace(/\${/g, '\\${')
          .replace(/\n/g, ' ')
          .replace(/\s+/g, ' ')
          .trim()
        cssContentMap[cssImport] = escapedCSS
        if (process.env.EXTENSION_ENV === 'development') {
          console.log(
            `[Extension.js] Read CSS content for ${cssImport}, length: ${cssContent.length}`
          )
        }
      } else {
        if (process.env.EXTENSION_ENV === 'development') {
          console.warn(`[Extension.js] CSS file not found: ${cssPath}`)
        }
      }
    } catch (error) {
      if (process.env.EXTENSION_ENV === 'development') {
        console.warn(
          `[Extension.js] Failed to read CSS file ${cssImport}:`,
          error
        )
      }
    }
  }

  // Generate TypeScript-compatible code for React
  const wrapperCode = `
// React Content Script Wrapper - Auto-generated by Extension.js
// This wrapper provides Shadow DOM isolation and CSS injection for React content scripts

// Original React content script source (directive processed)
${source.replace(/'use shadow-dom'/g, "// 'use shadow-dom'").replace(/"use shadow-dom"/g, '// "use shadow-dom"')}

// Content script options interface
export interface ContentScriptOptions {
  rootElement?: string
  rootClassName?: string
  stylesheets?: string[]
}

// Content script instance interface
export interface ContentScriptInstance {
  mount: (container: HTMLElement) => void
  unmount: () => void
}

// React Content script wrapper class
class ReactContentScriptWrapper {
  private rootElement: HTMLElement | null = null
  private shadowRoot: ShadowRoot | null = null
  private styleElement: HTMLStyleElement | null = null
  private renderFunction: (container: HTMLElement) => (() => void) | void
  private unmountFunction: (() => void) | null = null
  private options: ContentScriptOptions

  constructor(renderFunction: (container: HTMLElement) => (() => void) | void, options: ContentScriptOptions = {}) {
    this.renderFunction = renderFunction
    this.options = {
      rootElement: 'extension-root',
      rootClassName: undefined, // React handles its own styling
      stylesheets: ${JSON.stringify(cssImports.length > 0 ? cssImports : ['./styles.css'])},
      ...options
    }
  }

  async mount(container?: HTMLElement): Promise<void> {
    if (this.rootElement) {
      this.unmount()
    }

    // Create root element - React handles its own container styling
    this.rootElement = container || document.createElement('div')
    this.rootElement.id = this.options.rootElement!
    if (this.options.rootClassName) {
      this.rootElement.className = this.options.rootClassName
    }
    // React component handles its own styling

    // Create shadow root for style isolation
    this.shadowRoot = this.rootElement.attachShadow({ mode: 'open' })

    // Create a host element inside the shadow root for rendering
    const host = document.createElement('div')
    this.shadowRoot.appendChild(host)

    // Inject styles FIRST
    await this.injectStyles()

    // Render React content
    const result = this.renderFunction(host)
    if (typeof result === 'function') {
      this.unmountFunction = result
    }

    // Append to document if no container provided
    if (!container) {
      document.body.appendChild(this.rootElement)
    }
  }

  unmount() {
    if (this.unmountFunction) {
      this.unmountFunction()
      this.unmountFunction = null
    }

    if (this.rootElement && this.rootElement.parentNode) {
      this.rootElement.parentNode.removeChild(this.rootElement)
    }

    this.rootElement = null
    this.shadowRoot = null
    this.styleElement = null
  }

  // Inject styles with hardcoded CSS content for React templates
  private async injectStyles(): Promise<void> {
    const targetRoot = this.shadowRoot || this.rootElement!

    // Create style element
    this.styleElement = document.createElement('style')
    targetRoot.appendChild(this.styleElement)

    // Fetch CSS content
    try {
      const cssContent = await this.fetchCSS()
      this.styleElement.textContent = cssContent
    } catch (error) {
      console.error('[Extension.js] Failed to inject React CSS:', error)
    }

    // Setup HMR for CSS files
    this.setupCSSHMR()
  }

  // Fetch CSS with hardcoded content for React templates
  private async fetchCSS(): Promise<string> {
    let allCSS = ''

    // CSS content map is injected at build time
    const cssContentMap: Record<string, string> = ${JSON.stringify(cssContentMap)}

    for (const stylesheet of this.options.stylesheets) {
      try {
        // Check if we have hardcoded content for this stylesheet
        if (cssContentMap[stylesheet]) {
          const cssContent = cssContentMap[stylesheet]
          allCSS += cssContent + '\\n'
          continue
        }

        // For stylesheets without hardcoded content, try to fetch them
        const cssUrl = new URL(stylesheet, import.meta.url)
        const response = await fetch(cssUrl)
        const text = await response.text()
        if (response.ok) {
          allCSS += text + '\\n'
        } else {
          console.warn('[Extension.js] Failed to fetch CSS:', stylesheet)
        }
      } catch (error) {
        console.warn('[Extension.js] Failed to fetch React CSS:', stylesheet, error)
      }
    }

    const result = allCSS || '/* No CSS loaded */'
    return result
  }

  // Setup CSS HMR for React templates
  private setupCSSHMR() {
    if (!import.meta.webpackHot) return

    // Setup HMR for each CSS file
    for (const stylesheet of this.options.stylesheets) {
      import.meta.webpackHot?.accept(stylesheet, async () => {
        try {
          const cssContent = await this.fetchCSS()
          if (this.styleElement) {
            this.styleElement.textContent = cssContent
          }
        } catch (error) {
          console.error('[Extension.js] Failed to update React CSS via HMR:', stylesheet, error)
        }
      })
    }
  }
}

// Initialize React content script with wrapper
function initializeReactContentScript(
  options: ContentScriptOptions,
  renderFunction: (container: HTMLElement) => (() => void) | void
): ContentScriptInstance {
  const wrapper = new ReactContentScriptWrapper(renderFunction, options)
  
  return {
    mount: (container?: HTMLElement) => wrapper.mount(container),
    unmount: () => wrapper.unmount()
  }
}

// Auto-initialize the React content script with the wrapper
export function autoInitializeReactContentScript(
  options: ContentScriptOptions = {}
): ContentScriptInstance {
  // Get the render function from the imported contentScript
  const renderFunction = contentScript(options)

  // Initialize with the wrapper using the detected CSS imports
  return initializeReactContentScript(options, renderFunction)
}

// Simple initialization for React
let unmount: (() => void) | undefined

async function initialize() {
  if (unmount) {
    unmount()
  }
  
  // Get the render function from the contentScript function
  const renderFunction = contentScript({})
  const wrapper = new ReactContentScriptWrapper(renderFunction, {})
  await wrapper.mount()
  unmount = () => wrapper.unmount()
}

if (import.meta.webpackHot) {
  import.meta.webpackHot?.accept()
  import.meta.webpackHot?.dispose(() => unmount?.())

  // Accept changes to this file
  import.meta.webpackHot?.accept(() => {
    initialize()
  })
}

if (document.readyState === 'complete') {
  initialize()
} else {
  document.addEventListener('readystatechange', () => {
    if (document.readyState === 'complete') {
      initialize()
    }
  })
}

export default ReactContentScriptWrapper
`

  return wrapperCode
}
