#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATES_DIR="$ROOT_DIR/templates"
SCRIPTS_DIR="$ROOT_DIR/scripts"
REPO_URL="https://github.com/extension-js/examples"

has_required_templates() {
  local required=("typescript" "react" "svelte" "vue")
  for name in "${required[@]}"; do
    [[ -f "$TEMPLATES_DIR/$name/src/manifest.json" ]] || return 1
    [[ -f "$TEMPLATES_DIR/$name/template.spec.ts" ]] || return 1
    [[ -f "$TEMPLATES_DIR/$name/package.json" ]] || return 1
  done

  [[ -f "$TEMPLATES_DIR/extension-fixtures.ts" ]] || return 1
  [[ -f "$TEMPLATES_DIR/dirname.ts" ]] || return 1
  [[ -f "$SCRIPTS_DIR/build-with-manifest.mjs" ]] || return 1
}

if has_required_templates; then
  echo "Templates already hydrated. Skipping fetch."
  exit 0
fi

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

echo "Hydrating templates from extension-js/examples"
git clone --depth 1 "$REPO_URL" "$TMP_DIR/examples"

mkdir -p "$TEMPLATES_DIR" "$SCRIPTS_DIR"
cp -R "$TMP_DIR/examples/examples/." "$TEMPLATES_DIR/"
cp "$TMP_DIR/examples/ci-scripts/build-with-manifest.mjs" "$SCRIPTS_DIR/build-with-manifest.mjs" 2>/dev/null || true

# Generate a minimal package.json at templates/ root so spec helpers
# living one level above per-template folders (e.g. `templates/template.
# content-reload.spec.ts`) can resolve their non-workspace imports
# (`ws`, etc.). Without this file, Node's resolution walks up to the
# workspace root and `ws` — which is a transitive dep of programs/extension
# — is invisible to pnpm under default isolation.
#
# `"type": "module"` is REQUIRED: the workspace root sets type=module and
# the spec/helper files (`extension-fixtures.js`, `template.*.spec.ts`)
# use ESM syntax. Without it, this generated package.json shadows the
# root's type setting and Node interprets every `.js` under templates/
# as CJS, breaking named imports from `extension-fixtures.js` and the
# `import path from 'path'` form used across the spec files.
if [[ ! -f "$TEMPLATES_DIR/package.json" ]]; then
  cat > "$TEMPLATES_DIR/package.json" <<'JSON'
{
  "name": "@extension-js/templates-test-helpers",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "description": "Generated by scripts/hydrate-templates-from-examples.sh — local node_modules root for templates/*.spec.ts helpers (ws, etc).",
  "dependencies": {
    "ws": "^8.19.0"
  }
}
JSON
fi

# Each template under `templates/` is a standalone package — not part of
# the workspace — so its devDependencies (`preact`, `@tsconfig/svelte`,
# etc.) won't be installed by the workspace-level `pnpm install`.
# Without per-template installs, downstream `pnpm extension build
# templates/<name>` and the spec files that reference these templates
# fail to resolve modules. Install each template's deps (and the
# templates/-root helpers) now; cached on subsequent runs via the
# pnpm-store.
echo "Installing template dependencies..."
(
  cd "$TEMPLATES_DIR"
  pnpm install --ignore-workspace --prefer-offline --silent || {
    echo "warn: pnpm install failed in templates/ — continuing" >&2
  }
)
for template_dir in "$TEMPLATES_DIR"/*/; do
  [[ -f "$template_dir/package.json" ]] || continue
  (
    cd "$template_dir"
    # `--ignore-workspace` keeps the install scoped to the template; the
    # template's package.json is self-contained. `--prefer-offline` and
    # `--silent` keep the run fast and quiet on CI cache hits.
    pnpm install --ignore-workspace --prefer-offline --silent || {
      echo "warn: pnpm install failed in $(basename "$template_dir") — continuing" >&2
    }
  )
done

echo "Templates hydrated from extension-js/examples."
