#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TEMPLATES_DIR="$ROOT_DIR/templates"
SCRIPTS_DIR="$ROOT_DIR/scripts"
REPO_URL="https://github.com/extension-js/examples"

# Pin the examples ref so a readiness verdict maps to a known examples commit.
# Default stays `main` (prior behavior); set EXAMPLES_REF=<sha|tag|branch> in CI
# to make the acceptance/stability suites reproducible against a fixed point.
# The resolved SHA is written to templates/.examples-commit for the readiness
# document's `meta.examplesCommit` field.
EXAMPLES_REF="${EXAMPLES_REF:-main}"

has_required_templates() {
  local required=("typescript" "react" "svelte" "vue")
  for name in "${required[@]}"; do
    [[ -f "$TEMPLATES_DIR/$name/src/manifest.json" ]] || return 1
    [[ -f "$TEMPLATES_DIR/$name/template.spec.ts" ]] || return 1
    [[ -f "$TEMPLATES_DIR/$name/package.json" ]] || return 1
  done

  [[ -f "$TEMPLATES_DIR/extension-fixtures.ts" ]] || return 1
  [[ -f "$TEMPLATES_DIR/dirname.ts" ]] || return 1
  [[ -f "$SCRIPTS_DIR/build-with-manifest.mjs" ]] || return 1
}

if has_required_templates; then
  echo "Templates already hydrated. Skipping fetch."
  exit 0
fi

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

echo "Hydrating templates from extension-js/examples @ ${EXAMPLES_REF}"
# Shallow-clone the requested ref. A branch/tag clones directly; a full SHA
# (not a named ref) is fetched explicitly since `git clone --branch` rejects
# raw commit hashes.
if git clone --depth 1 --branch "$EXAMPLES_REF" "$REPO_URL" "$TMP_DIR/examples" 2>/dev/null; then
  :
else
  git clone "$REPO_URL" "$TMP_DIR/examples"
  git -C "$TMP_DIR/examples" checkout "$EXAMPLES_REF"
fi

mkdir -p "$TEMPLATES_DIR" "$SCRIPTS_DIR"
cp -R "$TMP_DIR/examples/examples/." "$TEMPLATES_DIR/"
cp "$TMP_DIR/examples/ci-scripts/build-with-manifest.mjs" "$SCRIPTS_DIR/build-with-manifest.mjs" 2>/dev/null || true

# Record the resolved examples commit so CI can stamp the readiness document.
git -C "$TMP_DIR/examples" rev-parse HEAD > "$TEMPLATES_DIR/.examples-commit"
echo "Pinned examples commit: $(cat "$TEMPLATES_DIR/.examples-commit")"

# Generate a minimal package.json at templates/ root so spec helpers
# living one level above per-template folders (e.g. `templates/template.
# content-reload.spec.ts`) can resolve their non-workspace imports
# (`ws`, etc.). Without this file, Node's resolution walks up to the
# workspace root and `ws` — which is a transitive dep of programs/extension
# — is invisible to pnpm under default isolation.
#
# `"type": "module"` is REQUIRED: the workspace root sets type=module and
# the spec/helper files (`extension-fixtures.js`, `template.*.spec.ts`)
# use ESM syntax. Without it, this generated package.json shadows the
# root's type setting and Node interprets every `.js` under templates/
# as CJS, breaking named imports from `extension-fixtures.js` and the
# `import path from 'path'` form used across the spec files.
if [[ ! -f "$TEMPLATES_DIR/package.json" ]]; then
  cat > "$TEMPLATES_DIR/package.json" <<'JSON'
{
  "name": "@extension-js/templates-test-helpers",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "description": "Generated by scripts/hydrate-templates-from-examples.sh — local node_modules root for templates/*.spec.ts helpers (ws, etc).",
  "dependencies": {
    "ws": "^8.19.0"
  }
}
JSON
fi

# Each template under `templates/` is a standalone package — not part of
# the workspace — so its devDependencies (`preact`, `@tsconfig/svelte`,
# etc.) won't be installed by the workspace-level `pnpm install`.
# Without per-template installs, downstream `pnpm extension build
# templates/<name>` and the spec files that reference these templates
# fail to resolve modules. Install each template's deps (and the
# templates/-root helpers) now; cached on subsequent runs via the
# pnpm-store.
echo "Installing template dependencies..."

# A quiet install keeps CI logs short, but it also hides why an install
# failed. On failure, retry once with full output: a registry hiccup (a
# just-published tarball that still returns 404) usually clears, and a real
# failure then shows pnpm's error instead of a later "module not found".
install_template_deps() {
  local label="$1"
  if pnpm install --ignore-workspace --prefer-offline --silent; then
    return 0
  fi
  echo "warn: pnpm install failed in ${label}, retrying once with full output" >&2
  sleep "${HYDRATE_INSTALL_RETRY_DELAY:-10}"
  if pnpm install --ignore-workspace --prefer-offline; then
    return 0
  fi
  echo "warn: pnpm install failed twice in ${label}, the error is above. Continuing." >&2
  return 0
}

(
  cd "$TEMPLATES_DIR"
  install_template_deps "templates/"
)
for template_dir in "$TEMPLATES_DIR"/*/; do
  [[ -f "$template_dir/package.json" ]] || continue
  (
    cd "$template_dir"
    # `--ignore-workspace` keeps the install scoped to the template, whose
    # package.json is self-contained. `--prefer-offline` keeps cache hits fast.
    install_template_deps "$(basename "$template_dir")"
  )
done

echo "Templates hydrated from extension-js/examples."
