name: CLI Command Tests

on:
  push:
    branches:
      - main
      - 'v[0-9]+.x'
  pull_request:
    branches:
      - main
      - 'v[0-9]+.x'

permissions:
  contents: read

jobs:
  test-commands:
    name: Test CLI Commands
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        node-version: [18]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Compile
        run: pnpm compile

      - name: Test CLI Commands
        run: pnpm test:cli

      - name: Test Create Command
        run: pnpm test:create

      - name: Test Build Command
        run: pnpm test:build

      # TODO: Uncomment when dev command is ready
      # - name: Test Dev Command
      #   run: pnpm test:dev

      # TODO: Uncomment when start command is ready
      # - name: Test Start Command
      #   run: pnpm test:start
