name: Sanity

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - 'v[0-9]+.x'

jobs:
  build:
    name: Build Extension.js
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '22'

      - name: Compile package
        run: pnpm compile

  test:
    name: Test
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '22'

      - name: Compile package
        run: pnpm compile

      - name: Test
        run: pnpm test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-22.04
    continue-on-error: true
    env:
      FORCE_COLOR: true
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '22'

      - name: Compile package
        run: pnpm compile

      - name: Run checks
        run: |
          pnpm format
          pnpm lint
          pnpm types
